version: '3'
services:
  db:
    image: blackjack-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blackjack-network
    command: --default-authentication-plugin=mysql_native_password

  php-server:
    image: blackjack-php-server
    build:
      context: ./server
    volumes:
      - ./server:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - blackjack-network

  react-client:
    image: blackjack-react-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - php-server
    networks:
      - blackjack-network

networks:
  blackjack-network:
