version: '3'
services:
  db:
    image: blackjack-db
    build:
      context: ./db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack_db
      MYSQL_USER: blackjack_user
      MYSQL_PASSWORD: blackjack_password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - blackjack-network

  php-server:
    image: blackjack-php-server
    build:
      context: ./server
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - blackjack-network

  react-client:
    image: blackjack-react-client
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - php-server
    networks:
      - blackjack-network

networks:
  blackjack-network:
